evenement_homepage:
    path:     /
    defaults: { _controller: EvenementBundle:Default:index }
aad:
    path:     /add-don
    defaults: { _controller: EvenementBundle:Don:add }
afficher:
    path:     /afficher
    defaults: { _controller: EvenementBundle:Don:afficher }
Delete:
    path:     /delete/{id}
    defaults: { _controller: EvenementBundle:Don:Delete }
map:
    path:     /map
    defaults: { _controller: EvenementBundle:Don:map }
pddf:
        path:     /test
        defaults: { _controller: EvenementBundle:Don:pddf }